### ISSUE TITLE
[Federation]: feddit.de: !physik, !mathematik, !raumfahrt, !robotik, !padel

### ISSUE THREAD

**Issue by marv-99** [Ategon/Lemmy-RemindMe-Bot#2]
### Instance

feddit.de

### Community Name

https://feddit.de/c/physik, https://feddit.de/c/raumfahrt, https://feddit.de/c/mathematik, https://feddit.de/c/robotik, https://feddit.de/c/padel

### Contact Information

https://feddit.de/u/marv99

**Comment by Ategon** [comment]
Added these to the whitelist
